### ISSUE TITLE
Update osv-scanner to v1.8.1

### ISSUE THREAD

**Issue by shahar-h** [google/osv-scanner-action#27]
Can you please release a new version that uses osv-scanner [v1.8.1](https://github.com/google/osv-scanner/releases/tag/v1.8.1)?
I want to use new `PackageOverrides` feature.

**Comment by shahar-h** [comment]
@another-rex is there going to be a new release soon?

**Comment by another-rex** [comment]
Sorry for the delay, there are some licensing issues around publishing to the GitHub Marketplace I am trying to resolve. The tag for v1.8.1 has already been made so feel free to use that directly.
