### ISSUE TITLE
Update osv-scanner to v1.9.1

### ISSUE THREAD

**Issue by shahar-h** [google/osv-scanner-action#51]
Can you please release a new version that uses osv-scanner [v1.9.1](https://github.com/google/osv-scanner/releases/tag/v1.9.1)?
I want to use new `vulnerabilities.ignore` feature  in package overrides

**Comment by another-rex** [comment]
Ah my bad, turns out I merged the PR https://github.com/google/osv-scanner-action/pull/49 a months ago, but never made the actual release tag. 🤦 

Release is made now!
